# Generated by Django 5.2.1 on 2025-07-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('income', 'Work/Salary'), ('income', 'Side Hustle'), ('income', 'Scholarship/Bursary'), ('income', 'Family Support'), ('income', 'Student Loan'), ('income', 'Grant'), ('income', 'Student Loan'), ('expense', 'Groceries'), ('expense', 'Rent/Accommodation'), ('expense', 'Transport'), ('expense', 'Data/Airtime'), ('expense', 'Gym/Fitness'), ('expense', 'Insurance'), ('expense', 'Debt Repayment'), ('expense', 'Entertainment'), ('expense', 'Eating Out'), ('expense', 'Education'), ('expense', 'Health/Medical'), ('expense', 'Clothing'), ('expense', 'Savings/Investments'), ('expense', 'Subscriptions')], default='Groaceries', max_length=22),
            preserve_default=False,
        ),
    ]
