# Generated by Django 5.2.1 on 2025-07-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('SALARY', 'Work/Salary'), ('SIDE_HUSTLE', 'Side Hustle'), ('BUSARY', 'Scholarship/Bursary'), ('ALLOWANCE', 'Family Support'), ('STUDENT_LOAN', 'Student Loan'), ('GRANT', 'Grant'), ('GIFT', 'Gift'), ('GROCERIES', 'Groceries'), ('RENT', 'Rent/Accommodation'), ('TRANSPORT', 'Transport'), ('DATA', 'Data/Airtime'), ('GYM', 'Gym/Fitness'), ('INSURANCE', 'Insurance'), ('DEBT', 'Debt Repayment'), ('ENTERTAINMENT', 'Entertainment'), ('DINING', 'Eating Out'), ('EDUCATION', 'Education'), ('HEALTH', 'Health/Medical'), ('CLOTHING', 'Clothing'), ('SAVINGS', 'Savings/Investments'), ('SUBSCRIPTIONS', 'Subscriptions')], default='SALARY', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('SALARY', 'Work/Salary'), ('SIDE_HUSTLE', 'Side Hustle'), ('BUSARY', 'Scholarship/Bursary'), ('ALLOWANCE', 'Family Support'), ('STUDENT_LOAN', 'Student Loan'), ('GRANT', 'Grant'), ('GIFT', 'Gift'), ('GROCERIES', 'Groceries'), ('RENT', 'Rent/Accommodation'), ('TRANSPORT', 'Transport'), ('DATA', 'Data/Airtime'), ('GYM', 'Gym/Fitness'), ('INSURANCE', 'Insurance'), ('DEBT', 'Debt Repayment'), ('ENTERTAINMENT', 'Entertainment'), ('DINING', 'Eating Out'), ('EDUCATION', 'Education'), ('HEALTH', 'Health/Medical'), ('CLOTHING', 'Clothing'), ('SAVINGS', 'Savings/Investments'), ('SUBSCRIPTIONS', 'Subscriptions')], max_length=22),
        ),
    ]
